name: 'Test ftqq message action'

on:
  push:
    branches:
      - master

jobs:
  test-massager:
    runs-on: ubuntu-18.04
    steps:
      - name: 'test'
        uses: lueyoung/ftqq-message-action@master
        with:
          sckey: ${{ secrets.SCKEY }}
          enable: true
          title: "test0x02"
          content: "test95271"
