name: 'Test ftqq message action'

on:
  push:
    branches:
      - master
      - dev

jobs:
  test-massager:
    runs-on: ubuntu-18.04
    steps:
      - name: 'test'
        uses: lueyoung/ftqq-message-action@dev
        with:
          sckey: ${{ secrets.SCKEY }}
          title: "test0x03"
          content: "test9527"
